language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  #- master
  - develop
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod


after_success:
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then 
        _FTP_USER=$FTP_USER
        _FTP_PASSWORD=$FTP_PASSWORD
     fi'
  - 'if [ "$TRAVIS_BRANCH" = "develop" ]; then 
        _FTP_USER=$FTP_DEVELOP_USER
        _FTP_PASSWORD=$FTP_DEVELOP_PASSWORD
    fi'


  - "find dist -type f -exec curl --ftp-create-dirs -T {} -u $_FTP_USER:$_FTP_PASSWORD ftp://$FTP_HOST/{} \\;"