language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  #- master
  - develop
before_script:
  - npm install -g @angular/cli
script:
- ng lint
- ng build --prod --base-href https://krystiansitarek.pl/


after_success:
  "find dist -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://$FTP_HOST/{} \\;"